[2022-02-19 15:46:23,933] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: configuration_dag.bash_task manual__2022-02-19T00:00:00+00:00 [queued]>
[2022-02-19 15:46:23,945] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: configuration_dag.bash_task manual__2022-02-19T00:00:00+00:00 [queued]>
[2022-02-19 15:46:23,946] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-19 15:46:23,946] {taskinstance.py:1239} INFO - Starting attempt 5 of 5
[2022-02-19 15:46:23,946] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-19 15:46:23,961] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): bash_task> on 2022-02-19 00:00:00+00:00
[2022-02-19 15:46:23,966] {standard_task_runner.py:52} INFO - Started process 3194 to run task
[2022-02-19 15:46:23,969] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'configuration_dag', 'bash_task', 'manual__2022-02-19T00:00:00+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/configuration_dag.py', '--cfg-path', '/tmp/tmpgfrvk8zr', '--error-file', '/tmp/tmpxzitm2gx']
[2022-02-19 15:46:23,969] {standard_task_runner.py:77} INFO - Job 22: Subtask bash_task
[2022-02-19 15:46:24,027] {logging_mixin.py:109} INFO - Running <TaskInstance: configuration_dag.bash_task manual__2022-02-19T00:00:00+00:00 [running]> on host 38342be44bf7
[2022-02-19 15:46:24,084] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=configuration_dag
AIRFLOW_CTX_TASK_ID=bash_task
AIRFLOW_CTX_EXECUTION_DATE=2022-02-19T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-02-19T00:00:00+00:00
[2022-02-19 15:46:24,085] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-02-19 15:46:24,086] {subprocess.py:74} INFO - Running command: ['bash', '-c', '/usr/local/spark/configure.sh ']
[2022-02-19 15:46:24,099] {subprocess.py:85} INFO - Output:
[2022-02-19 15:46:27,171] {subprocess.py:89} INFO - A connection with `conn_id`=spark_default already exists.
[2022-02-19 15:46:31,185] {subprocess.py:89} INFO - [[34m2022-02-19 15:46:31,185[0m] {[34mcrypto.py:[0m82} WARNING[0m - empty cryptography key - values will not be stored encrypted.[0m
[2022-02-19 15:46:31,191] {subprocess.py:89} INFO - A connection with `conn_id`=minio_default already exists.
[2022-02-19 15:46:34,612] {subprocess.py:89} INFO - [[34m2022-02-19 15:46:34,612[0m] {[34mcrypto.py:[0m82} WARNING[0m - empty cryptography key - values will not be stored encrypted.[0m
[2022-02-19 15:46:34,617] {subprocess.py:89} INFO - A connection with `conn_id`=cassandra_default already exists.
[2022-02-19 15:46:36,613] {subprocess.py:89} INFO - Installed kernelspec python3 in /home/***/.local/share/jupyter/kernels/python3
[2022-02-19 15:46:36,767] {subprocess.py:93} INFO - Command exited with return code 0
[2022-02-19 15:46:36,871] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=configuration_dag, task_id=bash_task, execution_date=20220219T000000, start_date=20220219T154623, end_date=20220219T154636
[2022-02-19 15:46:36,945] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-19 15:46:37,019] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
