[2022-02-10 14:53:14,244] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: spark-test-cassandra.spark_job manual__2022-02-10T14:53:12.200976+00:00 [queued]>
[2022-02-10 14:53:14,261] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: spark-test-cassandra.spark_job manual__2022-02-10T14:53:12.200976+00:00 [queued]>
[2022-02-10 14:53:14,261] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-10 14:53:14,261] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-02-10 14:53:14,261] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-10 14:53:14,287] {taskinstance.py:1259} INFO - Executing <Task(SparkSubmitOperator): spark_job> on 2022-02-10 14:53:12.200976+00:00
[2022-02-10 14:53:14,292] {standard_task_runner.py:52} INFO - Started process 70 to run task
[2022-02-10 14:53:14,296] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'spark-test-cassandra', 'spark_job', 'manual__2022-02-10T14:53:12.200976+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/spark-cassandra-dag.py', '--cfg-path', '/tmp/tmp85ltld2y', '--error-file', '/tmp/tmp_6c7ffav']
[2022-02-10 14:53:14,296] {standard_task_runner.py:77} INFO - Job 2: Subtask spark_job
[2022-02-10 14:53:14,354] {logging_mixin.py:109} INFO - Running <TaskInstance: spark-test-cassandra.spark_job manual__2022-02-10T14:53:12.200976+00:00 [running]> on host fbeb6ce81a93
[2022-02-10 14:53:14,418] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@***.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=spark-test-cassandra
AIRFLOW_CTX_TASK_ID=spark_job
AIRFLOW_CTX_EXECUTION_DATE=2022-02-10T14:53:12.200976+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-02-10T14:53:12.200976+00:00
[2022-02-10 14:53:14,429] {spark_submit.py:229} INFO - Could not load connection string spark_default, defaulting to yarn
[2022-02-10 14:53:14,430] {spark_submit.py:360} INFO - Spark-Submit cmd: spark-submit --master yarn --conf spark.master=spark://spark:7077 --name Spark test cassandra --verbose /usr/local/spark/app/spark-cassandra-test.py
[2022-02-10 14:53:16,056] {spark_submit.py:514} INFO - Using properties file: null
[2022-02-10 14:53:16,164] {spark_submit.py:514} INFO - WARNING: An illegal reflective access operation has occurred
[2022-02-10 14:53:16,164] {spark_submit.py:514} INFO - WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/home/***/.local/lib/python3.7/site-packages/pyspark/jars/spark-unsafe_2.12-3.0.0.jar) to constructor java.nio.DirectByteBuffer(long,int)
[2022-02-10 14:53:16,164] {spark_submit.py:514} INFO - WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
[2022-02-10 14:53:16,164] {spark_submit.py:514} INFO - WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[2022-02-10 14:53:16,164] {spark_submit.py:514} INFO - WARNING: All illegal access operations will be denied in a future release
[2022-02-10 14:53:16,225] {spark_submit.py:514} INFO - Exception in thread "main" org.apache.spark.SparkException: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
[2022-02-10 14:53:16,225] {spark_submit.py:514} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:630)
[2022-02-10 14:53:16,225] {spark_submit.py:514} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:270)
[2022-02-10 14:53:16,225] {spark_submit.py:514} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:233)
[2022-02-10 14:53:16,226] {spark_submit.py:514} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:119)
[2022-02-10 14:53:16,226] {spark_submit.py:514} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:990)
[2022-02-10 14:53:16,226] {spark_submit.py:514} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:990)
[2022-02-10 14:53:16,226] {spark_submit.py:514} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:85)
[2022-02-10 14:53:16,226] {spark_submit.py:514} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1007)
[2022-02-10 14:53:16,226] {spark_submit.py:514} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1016)
[2022-02-10 14:53:16,226] {spark_submit.py:514} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2022-02-10 14:53:16,266] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 182, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 446, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --conf spark.master=spark://spark:7077 --name Spark test cassandra --verbose /usr/local/spark/app/spark-cassandra-test.py. Error code is: 1.
[2022-02-10 14:53:16,275] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=spark-test-cassandra, task_id=spark_job, execution_date=20220210T145312, start_date=20220210T145314, end_date=20220210T145316
[2022-02-10 14:53:16,291] {standard_task_runner.py:92} ERROR - Failed to execute job 2 for task spark_job
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 182, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 446, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --conf spark.master=spark://spark:7077 --name Spark test cassandra --verbose /usr/local/spark/app/spark-cassandra-test.py. Error code is: 1.
[2022-02-10 14:53:16,312] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-02-10 14:53:16,356] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
