[2022-02-19 14:41:06,217] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: configuration_dag.bash_task scheduled__2020-01-01T00:00:00+00:00 [queued]>
[2022-02-19 14:41:06,249] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: configuration_dag.bash_task scheduled__2020-01-01T00:00:00+00:00 [queued]>
[2022-02-19 14:41:06,249] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-19 14:41:06,249] {taskinstance.py:1239} INFO - Starting attempt 2 of 2
[2022-02-19 14:41:06,249] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-19 14:41:06,273] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): bash_task> on 2020-01-01 00:00:00+00:00
[2022-02-19 14:41:06,279] {standard_task_runner.py:52} INFO - Started process 545 to run task
[2022-02-19 14:41:06,286] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'configuration_dag', 'bash_task', 'scheduled__2020-01-01T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/configuration_dag.py', '--cfg-path', '/tmp/tmpv95wlc99', '--error-file', '/tmp/tmp9sao5tf5']
[2022-02-19 14:41:06,287] {standard_task_runner.py:77} INFO - Job 11: Subtask bash_task
[2022-02-19 14:41:06,368] {logging_mixin.py:109} INFO - Running <TaskInstance: configuration_dag.bash_task scheduled__2020-01-01T00:00:00+00:00 [running]> on host 38342be44bf7
[2022-02-19 14:41:06,461] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=configuration_dag
AIRFLOW_CTX_TASK_ID=bash_task
AIRFLOW_CTX_EXECUTION_DATE=2020-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-01-01T00:00:00+00:00
[2022-02-19 14:41:06,463] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-02-19 14:41:06,463] {subprocess.py:74} INFO - Running command: ['bash', '-c', '/usr/local/spark/configure.sh ']
[2022-02-19 14:41:06,484] {subprocess.py:85} INFO - Output:
[2022-02-19 14:41:10,139] {subprocess.py:89} INFO - A connection with `conn_id`=spark_default already exists.
[2022-02-19 14:41:13,647] {subprocess.py:89} INFO - [[34m2022-02-19 14:41:13,647[0m] {[34mcrypto.py:[0m82} WARNING[0m - empty cryptography key - values will not be stored encrypted.[0m
[2022-02-19 14:41:13,662] {subprocess.py:89} INFO - A connection with `conn_id`=minio_default already exists.
[2022-02-19 14:41:17,763] {subprocess.py:89} INFO - [[34m2022-02-19 14:41:17,763[0m] {[34mcrypto.py:[0m82} WARNING[0m - empty cryptography key - values will not be stored encrypted.[0m
[2022-02-19 14:41:17,770] {subprocess.py:89} INFO - A connection with `conn_id`=cassandra_default already exists.
[2022-02-19 14:41:19,581] {subprocess.py:89} INFO - Installed kernelspec python3 in /home/***/.local/share/jupyter/kernels/python3
[2022-02-19 14:41:19,684] {subprocess.py:93} INFO - Command exited with return code 0
[2022-02-19 14:41:19,708] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=configuration_dag, task_id=bash_task, execution_date=20200101T000000, start_date=20220219T144106, end_date=20220219T144119
[2022-02-19 14:41:19,734] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-19 14:41:19,761] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
