[2022-02-19 01:03:44,176] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: configuration_dag.bash_task manual__2022-02-19T01:03:43.289442+00:00 [queued]>
[2022-02-19 01:03:44,192] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: configuration_dag.bash_task manual__2022-02-19T01:03:43.289442+00:00 [queued]>
[2022-02-19 01:03:44,192] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-19 01:03:44,192] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-19 01:03:44,192] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-19 01:03:44,210] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): bash_task> on 2022-02-19 01:03:43.289442+00:00
[2022-02-19 01:03:44,215] {standard_task_runner.py:52} INFO - Started process 634 to run task
[2022-02-19 01:03:44,219] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'configuration_dag', 'bash_task', 'manual__2022-02-19T01:03:43.289442+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/configuration_dag.py', '--cfg-path', '/tmp/tmpeh_mf657', '--error-file', '/tmp/tmpyh9k8kih']
[2022-02-19 01:03:44,220] {standard_task_runner.py:77} INFO - Job 3: Subtask bash_task
[2022-02-19 01:03:44,297] {logging_mixin.py:109} INFO - Running <TaskInstance: configuration_dag.bash_task manual__2022-02-19T01:03:43.289442+00:00 [running]> on host 4861cc27bfb2
[2022-02-19 01:03:44,371] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=configuration_dag
AIRFLOW_CTX_TASK_ID=bash_task
AIRFLOW_CTX_EXECUTION_DATE=2022-02-19T01:03:43.289442+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-02-19T01:03:43.289442+00:00
[2022-02-19 01:03:44,372] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-02-19 01:03:44,373] {subprocess.py:74} INFO - Running command: ['bash', '-c', '/usr/local/spark/configure.sh ']
[2022-02-19 01:03:44,383] {subprocess.py:85} INFO - Output:
[2022-02-19 01:03:47,583] {subprocess.py:89} INFO - A connection with `conn_id`=spark_default already exists.
[2022-02-19 01:03:51,245] {subprocess.py:89} INFO - [[34m2022-02-19 01:03:51,245[0m] {[34mcrypto.py:[0m82} WARNING[0m - empty cryptography key - values will not be stored encrypted.[0m
[2022-02-19 01:03:51,251] {subprocess.py:89} INFO - A connection with `conn_id`=minio_default already exists.
[2022-02-19 01:03:54,499] {subprocess.py:89} INFO - [[34m2022-02-19 01:03:54,499[0m] {[34mcrypto.py:[0m82} WARNING[0m - empty cryptography key - values will not be stored encrypted.[0m
[2022-02-19 01:03:54,505] {subprocess.py:89} INFO - A connection with `conn_id`=cassandra_default already exists.
[2022-02-19 01:03:56,434] {subprocess.py:89} INFO - Installed kernelspec python3 in /home/***/.local/share/jupyter/kernels/python3
[2022-02-19 01:03:56,564] {subprocess.py:93} INFO - Command exited with return code 0
[2022-02-19 01:03:56,593] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=configuration_dag, task_id=bash_task, execution_date=20220219T010343, start_date=20220219T010344, end_date=20220219T010356
[2022-02-19 01:03:56,638] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-19 01:03:56,668] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
